const appLanguage:any = {
  ru:{
    logout: "выход",
    login: "Войти через Google",
    popular: "Популярные",
    recent: "Последние",
    addReview: "+ Создать обзор",
    newReview: "Новый обзор",
    reviewName: "Название обзора",
    tags: "Тэги",
    images: "Изображения",
    reviewScore: "Оценка ревью",
    changeTitle: "Изменить тему",
    createReview: "Создать обзор",
    profile: "Профиль",
    totalReviews: "Количество обзоров",
    registrationDate: "Дата регистрации",
    lastLoginDate: "Дата последнего входа",
    adminPanel: "Панель администратора",
    admin: "Админ",
    selectAll: "Выделить всех",
    unSelectAll: "Снять выделение",
    user: "Пользователь",
    role: "Роль",
    status: "Статус",
    rating: "Рейтинг",
    block: "Заблокировать",
    unblock: "Разблокировать",
    delete: "Удалить"
  },
  en:{
    logout: "log out",
    login: "Login with Google",
    popular: "Popular",
    recent: "Recent",
    addReview: "+ Add review",
    newReview: "New review",
    reviewName: "Review name",
    tags: "Tags",
    images: "Images",
    reviewScore: "Review score",
    changeTitle: "change title",
    createReview: "Create review",
    profile: "Profile",
    totalReviews: "Total reviews",
    registrationDate: "Registration date",
    lastLoginDate: "Last login date",
    adminPanel: "Admin panel",
    admin: "Admin",
    selectAll: "Select all",
    unSelectAll: "Unselect all",
    user: "User",
    role: "Role",
    status: "Status",
    rating: "Rating",
    block: "Block",
    unblock: "Unblock",
    delete: "Delete"
  }
}

export default appLanguage

